redash:
  image: redash/redash:0.10.0.b1674
  # Uncomment the following line and comment out the above line
  # to build from source instead of Docker hub
  # build: .
  ports:
    - "5000:5000"
  volumes:
    - .:/opt/redash/current
  links:
    - redis
    - postgres
  external_links:
    - api_influxdb_1:influxdb
  environment:
    REDASH_STATIC_ASSETS_PATH: "../rd_ui/dist/"
    REDASH_LOG_LEVEL: "INFO"
    REDASH_REDIS_URL: "redis://redis:6379/0"
    REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
    REDASH_COOKIE_SECRET: veryverysecret

redis:
  image: redis:2.8

postgres:
  image: postgres:9.3
